---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-paginate


### content configuration ###
title:       "Scenarioo - Automated Documentation with UI Tests"
keywords:    "Scenarioo, Open Source, Documentation, User Interface, UI Tests, Automated Documentation, Living Documentation, Testing, User Scenario, Use Case, Webapplication, Desktop, Mobile, Selenium, Github"
description: "With Scenarioo you can turn the UI tests of your application into a powerful documentation about the functionalities of your application, that is helpful for all involved people in your project. Users can browse the tested user scenarios of all use cases with the current screenshots and additional information. "
source_link: "https://github.com/scenarioo"
favicon:     "img/favicon.ico"
touch_icon:  "img/touchicon.png"
google_analytics_key: "UA-21795453-5"

collections:
  tutorial_sections:
    output: true

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gray:      '#666666'
  lightGray: '#f0f0f0'
  sectionTitleColor: '#555555'



kramdown:
  input: GFM
  auto_ids:  false
